version: '3'

services:
  postgres-ddosaas:
    container_name: "postgres-ddosaas"
    image: postgres:13-alpine3.20
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ddosaas
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  central:
    image: ddosaas-central:local
    container_name: ddosaas-central
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ddosaas:5432/ddosaas
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  # dbeaver:
  #   container_name: dbeaver-dev
  #   image: dbeaver/cloudbeaver:23.3.2
  #   ports:
  #     - "15434:8978"
  #   volumes:
  #     - /dbeaver:/opt/cloudbeaver/workspace      