version: '3'

services:
  postgres-ddosaas:
    container_name: "postgres-ddosaas"
    image: postgres:13-alpine3.20
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ddosaas
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  