services:

  attacker:
    image: gabrielborgesdocker/ppee:attacker-1.0.0
    container_name: ddosaas-attacker
    # ports:
    #   - "8080:8080"
    environment:
      internalToken: token_to_be_replaced
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik"

    - "traefik.http.routers.attacker.entrypoints=websecure"
    - "traefik.http.routers.attacker.tls=true"
    - "traefik.http.routers.attacker.tls.certresolver=le"
    - "traefik.http.routers.attacker.rule=Host(`cti-attacker.ppee-unb.com.br`)"
    - "traefik.http.services.attacker.loadbalancer.server.port=8081"
    - "traefik.http.routers.attacker.service=attacker"
    networks:
    - traefik

  traefik:
    image: traefik:v2.9.5
    container_name: traefik
    hostname: traefik
    command:
    # - --log.level=DEBUG
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.web.http.redirections.entrypoint.permanent=true
    - --certificatesresolvers.le.acme.email=ddosaas.ppee.unb@gmail.com
    - --certificatesresolvers.le.acme.storage=acme.json
    - --certificatesresolvers.le.acme.tlschallenge=true
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "/data/letsencrypt/acme.json:/acme.json"
    environment:
    - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
    - traefik      

  portainer:
    image: portainer/portainer-ce:2.20.3
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.rule=Host(`portainer-worker.ppee-unb.com.br`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
    networks:
      - traefik

volumes:
  portainer_data:

networks:
  traefik:
    external: true  
